spring:
  kafka:
    bootstrap-servers: localhost:9095
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#By default all camel endpoints are mapped to route /camel ... if i want to change it to /, then i need to use docs below
#aslo i need to specify in swagger root path
#camel:
#  servlet:
#    mapping:
#      context-path: /*

logging:
  config: classpath:log4j2.xml
  level:
    io.swagger: DEBUG
    com.gamingtec.services: INFO
    org.apache.camel: INFO