#spring:
#  kafka:
#    bootstrap-servers: localhost:9095
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
camel:
  component:
    kafka:
      brokers: localhost:9095
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer

#      transaction-id-prefix: tx-
#      group-id: group_id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer


logging:
  config: classpath:log4j2.xml

server:
  port: ${WEB_PORT:8083}