syntax = "proto3";
//import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

package com.gamingtec.wallet;

message BalanceRequestGrpc {
  uint32 partyId = 1;
  uint32 brandId = 2;
  string gameId = 3;
  string platformCode = 4;
  string playerCurrency = 5;
  uint32 numDecimalParts = 6;
}

message BalanceGrpc{
  uint32 accountId = 1;
  uint32 partyId = 2;
  DecimalValue real = 3;
  DecimalValue releasedBonus = 4;
  DecimalValue playableBonus = 5;
}

message BetRequestGrpc{
  uint32 partyId = 1;
  uint32 platformId = 2;
  string platformCode = 3;
  string gameId = 4;
  uint32 gameInfoId = 5;
  bool sportbook = 6;
  string playerCurrency = 7;
  string platformGameTranId = 8;
  string platformTranId = 9;
  DecimalValue amount = 10;
}

message BetResponseGrpc{
  BalanceGrpc balance = 1;
  uint64 transactionId = 2;
}

message DecimalValue {
  uint32 scale = 1;
  uint32 precision = 2;
  bytes value = 3;
}

message OptionalUInt64Value {
  google.protobuf.UInt64Value result = 1;
}

message OptionalUInt32Value {
  google.protobuf.UInt32Value result = 1;
}

message OptionalStringValue{
  google.protobuf.StringValue result = 1;
}