#spring:
#  kafka:
#    bootstrap-servers: localhost:9095
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: com.gamingtec.services.event.kafka.serializers.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: com.gamingtec.services.event.kafka.serializers.JsonSerializer

#      group-id: group_id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer


spring:
  application:
    name: "wallet"
  data:
    redis:
      host: localhost
      database: 0
      port: 6379

camel:
  component:
    kafka:
      brokers: localhost:9095
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  config: classpath:log4j2.xml
  level:
    org.springframework.kafka: info
    org.springframework.transaction: trace
    org.springframework.kafka.transaction: debug

server:
  port: ${WEB_PORT:8082}
grpc:
  server:
    port: ${GRPC_PORT:9899}